{
 "title": "SMF dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "plmnid", "label": "PLMN", "query": { "query": "label_values(plmnid)" } },
   { "name": "snssai", "label": "S-NSSAI", "query": { "query": "label_values(snssai)" } },
   { "name": "fiveqi", "label": "5QI", "query": { "query": "label_values(fiveqi)" } }
  ]
 },
 "panels": [
  {
   "title": "PDU Session Creation Req",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=\"fivegs_smffunction_sm_pdusessioncreationreq\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMF Active Sessions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"ues_active\", instance=\"smf1.open5gs.org:9090\", job=\"smf1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"ues_active\", instance=\"smf2.open5gs.org:9090\", job=\"smf2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"ues_active\", instance=\"smf3.open5gs.org:9090\", job=\"smf3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"ues_active\", instance=\"smf4.open5gs.org:9090\", job=\"smf4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"ues_active\", instance=\"smf5.open5gs.org:9090\", job=\"smf5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMF PDU Session Create requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "fivegs_smffunction_sm_qos_flow_nbr",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_smffunction_sm_pdusessioncreationreq{job=\"smf\",plmnid=\"$plmnid\",snssai=\"$snssai\"}",
     "legendFormat": "SMF PDU Session Create requests for PLMN {{plmnid}} and S-NSSAI {{snssai}}"
    }
   ]
  },
  {
   "title": "SMF PDU Session Creation Req",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "fivegs_smffunction_sm_pdusessioncreationreq",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMF-5 Session Report ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{__name__=\"fivegs_smffunction_sm_n4sessionreport\", instance=\"smf5.open5gs.org:9090\", job=\"smf5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMF-5 Active UE's",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{__name__=\"ues_active\", instance=\"smf5.open5gs.org:9090\", job=\"smf5\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}