{
 "title": "PCF dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "plmnid", "label": "PLMN", "query": { "query": "label_values(plmnid)" } },
   { "name": "snssai", "label": "S-NSSAI", "query": { "query": "label_values(snssai)" } }
  ]
 },
 "panels": [
  {
   "title": "Policy Successful",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "fivegs_pcffunction_pa_policysmassosucc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCF SM Policy Association requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(fivegs_pcffunction_pa_policysmassoreq{job=\"pcf\",plmnid=\"$plmnid\"}) by (plmnid)",
     "legendFormat": "PCF SM Policy Association requests for PLMN {{plmnid}}"
    },
    {
     "expr": "fivegs_pcffunction_pa_policysmassoreq{job=\"pcf\",plmnid=\"$plmnid\",snssai=\"$snssai\"}",
     "legendFormat": "PCF SM Policy Association requests for PLMN {{plmnid}} and S-NSSAI {{snssai}}"
    }
   ]
  },
  {
   "title": "PCF Function PA Sessionbr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "fivegs_pcffunction_pa_sessionnbr",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policy Asasso Req",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "fivegs_pcffunction_pa_policyamassoreq",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}