{
 "title": "UPF dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dnn", "label": "DNN", "query": { "query": "label_values(dnn)" } }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "alertlist",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ALERTS_FOR_STATE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UPF number of QoS flows (upf1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "fivegs_upffunction_upf_qosflows{job=\"upf1\"}",
     "legendFormat": "UPF number of QoS flows"
    },
    {
     "expr": "fivegs_upffunction_upf_qosflows{job=\"upf1\",dnn=\"$dnn\"}",
     "legendFormat": "UPF number of QoS flows for DNN {{dnn}}"
    }
   ]
  },
  {
   "title": "UPF number of QoS flows (upf2)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "fivegs_upffunction_upf_qosflows{job=\"upf2\"}",
     "legendFormat": "UPF number of QoS flows"
    },
    {
     "expr": "fivegs_upffunction_upf_qosflows{job=\"upf2\",dnn=\"$dnn\"}",
     "legendFormat": "UPF number of QoS flows for DNN {{dnn}}"
    }
   ]
  },
  {
   "title": "UPF number of QoS flows (upf3)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "fivegs_upffunction_upf_qosflows{job=\"upf3\"}",
     "legendFormat": "UPF number of QoS flows"
    },
    {
     "expr": "fivegs_upffunction_upf_qosflows{job=\"upf3\",dnn=\"$dnn\"}",
     "legendFormat": "UPF number of QoS flows for DNN {{dnn}}"
    }
   ]
  },
  {
   "title": "UPF number of QoS flows (upf4)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "fivegs_upffunction_upf_qosflows{job=\"upf4\"}",
     "legendFormat": "UPF number of QoS flows"
    },
    {
     "expr": "fivegs_upffunction_upf_qosflows{job=\"upf4\",dnn=\"$dnn\"}",
     "legendFormat": "UPF number of QoS flows for DNN {{dnn}}"
    }
   ]
  },
  {
   "title": "UPF number of QoS flows (upf5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "fivegs_upffunction_upf_qosflows{job=\"upf5\"}",
     "legendFormat": "UPF number of QoS flows"
    },
    {
     "expr": "fivegs_upffunction_upf_qosflows{job=\"upf5\",dnn=\"$dnn\"}",
     "legendFormat": "UPF number of QoS flows for DNN {{dnn}}"
    }
   ]
  }
 ]
}