{
 "title": "AMF dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "plmnid", "label": "PLMN", "query": { "query": "label_values(plmnid)" } },
   { "name": "snssai", "label": "S-NSSAI", "query": { "query": "label_values(snssai)" } }
  ]
 },
 "panels": [
  {
   "title": "AMF Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "amf_session{instance=\"amf1.open5gs.org:9090\", job=\"amf1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "amf_session{instance=\"amf2.open5gs.org:9090\", job=\"amf2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "amf_session{instance=\"amf3.open5gs.org:9090\", job=\"amf3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMF-1 gnb's",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"gnb\", instance=\"amf1.open5gs.org:9090\", job=\"amf1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMF Initial Registration requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "fivegs_amffunction_rm_reginitreq{job=\"amf1\"}",
     "legendFormat": "AMF Initial Registration requests"
    },
    {
     "expr": "fivegs_amffunction_rm_reginitsucc{job=\"amf\"}",
     "legendFormat": "AMF successful Initial Registration requests"
    },
    {
     "expr": "fivegs_amffunction_rm_reginitreq{job=\"amf2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_amffunction_rm_reginitreq{job=\"amf3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMF-2 gnb's",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"gnb\", instance=\"amf2.open5gs.org:9090\", job=\"amf2\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMF Authentication requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "fivegs_amffunction_amf_authreq{job=\"amf1\"}",
     "legendFormat": "AMF Authentication requests"
    },
    {
     "expr": "fivegs_amffunction_amf_authreject{job=\"amf1\"}",
     "legendFormat": "AMF Authentication rejects"
    },
    {
     "expr": "fivegs_amffunction_amf_authreq{job=\"amf2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_amffunction_amf_authreject{job=\"amf2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_amffunction_amf_authreq{job=\"amf3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_amffunction_amf_authreject{job=\"amf3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMF-3 gnb's",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"gnb\", instance=\"amf3.open5gs.org:9090\", job=\"amf3\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}