{
 "title": "Processor_Usage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "UPF's Processor Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=\"process_cpu_seconds_total\", instance=\"upf1.open5gs.org:9090\", job=\"upf1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"process_cpu_seconds_total\", instance=\"upf2.open5gs.org:9090\", job=\"upf2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"process_cpu_seconds_total\", instance=\"upf3.open5gs.org:9090\", job=\"upf3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"process_cpu_seconds_total\", instance=\"upf4.open5gs.org:9090\", job=\"upf4\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMF's Processor Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=\"process_cpu_seconds_total\", instance=\"amf1.open5gs.org:9090\", job=\"amf1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"process_cpu_seconds_total\", instance=\"amf2.open5gs.org:9090\", job=\"amf2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"process_cpu_seconds_total\", instance=\"amf3.open5gs.org:9090\", job=\"amf3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMF's Processor Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{__name__=\"process_cpu_seconds_total\", instance=\"smf1.open5gs.org:9090\", job=\"smf1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"process_cpu_seconds_total\", instance=\"smf2.open5gs.org:9090\", job=\"smf2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"process_cpu_seconds_total\", instance=\"smf3.open5gs.org:9090\", job=\"smf3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"process_cpu_seconds_total\", instance=\"smf4.open5gs.org:9090\", job=\"smf4\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Network Receive Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{__name__=\"container_network_receive_bytes_total\", id=\"/\", instance=\"cadvisor:8080\", interface=\"br-ogs\", job=\"cadvisor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"container_network_receive_bytes_total\", id=\"/\", instance=\"cadvisor:8080\", interface=\"eth0\", job=\"cadvisor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Network Receive Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processor CPU (SMF-5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{__name__=\"process_cpu_seconds_total\", instance=\"smf5.open5gs.org:9090\", job=\"smf5\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}